### ISSUE TITLE
夜间模式下发布动态 选择编辑文字 选中阴影和背景颜色一样 融为一体

### ISSUE THREAD

**Issue by a328661276** [AlexVincent525/OpenJMU#18]

**Comment by a328661276** [comment]
![8YTHQ319VA8UAZJ@2~GAA](https://user-images.githubusercontent.com/38584538/55685244-6797c480-5986-11e9-8771-93adbdebd45e.jpg)
![@~RW0Q ZYW J3Z)_7MUC9XP](https://user-images.githubusercontent.com/38584538/55685245-6cf50f00-5986-11e9-9802-a08596b4a83e.jpg)

**Comment by AlexVincent525** [comment]
Fixed in next release.
![image](https://user-images.githubusercontent.com/15884415/56502335-7d1dfa00-6501-11e9-9876-e8a0ad0953dc.png)
